org: lucasaliaga
service: api-compras

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::214817148898:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_compras

functions:
  registrarCompra:
    handler: lambda.registrar_compra
    events:
      - http:
          path: /compras/registrar
          method: post
          cors: true

  listarCompras:
    handler: lambda.listar_compras
    events:
      - http:
          path: /compras/listar
          method: post
          cors: true

resources:
  Resources:
    TablaCompras:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: usuario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
